### ISSUE TITLE
Mark homework1, exercise3 of rebecca-post

### ISSUE THREAD

**Issue by rebeccapost** [rebeccapost/stat679work#2]
## Mark Homework 1, Exercise 3: @cecileane

revision SHA: https://github.com/rebeccapost/stat679work/commit/9213b32e4039c917187f5cc0e238a6ac9978ad91

This homework script assumes that the script is run from the directory that contains the data directory. By this, I mean that my script calls hw1-snaqTimeTests/log and hw1-snaqTimeTests/out.

summarizeSNaQres.sh creates a csv file (summarizeSNaQres.csv) that summarizes information about the analyses in the data file.

**Comment by cecileane** [comment]
Thanks Rebacca! This is my way of asking William (@mortonwilliam) and Alex (@ajschmidt01) to try your script and provide feedback on it.

**Comment by mortonwilliam** [comment]
Hello Rebecca, 

I think your scripts are very easy to follow especially with the detailed comments you left after lines to explain their function. These comments were descriptive yet concise and very user friendly. Your use of sed I think simplified things better as well. 

In general, I think your code is very clean making it easy to understand. I probably ended up learning quite a bit, especially in the way your set up the ‘if - then’ statements

GREAT WORK!

**Comment by ajschmidt01** [comment]
Hi Rebecca,

I ran the scripts, and they all worked as intended. The script is very clean! The variable names were clear, and each step of the script file was straightforward. I especially enjoyed seeing how you created the under3460 variables. I used a set of “sed” commands to restrict the output to values under the threshold, but the set of if statements you use is very efficient. 

The readme file is very well documented. It is clear where the data came from, what the files do, and how to run everything. I like the section that clearly states what is important to know before running the scripts. Very helpful. 

A few minor suggestions:
1. Your script, like mine, requires that you run the script while in a specific directory. This requirement was well documented in both the readme file and the script itself.  One addition you could consider in the future is a check that ensures that the user is running the file in the correct directory. I did this by saving the current directory, and then including an if statement checking if the current directory is the correct directory, returning an error statement if not.  
2. Another very small suggestion: in the script, you move into the log directory to grab the data. For convenience, you may want to end the script by moving back into the starting directory. 
3. Finally, you may consider including more directories in your project folders (e.g., data, scripts, results, etc.)  This project is quite small, so organization is not too difficult, but it may be helpful for keeping items separate in more complex projects. 

Great job! I really enjoyed seeing how you approached the problem, and learned a lot from your code!
